/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nghia
 */
public class Table extends javax.swing.JFrame {

    int length;
    Vector vctHeader = new Vector();
    Vector vctData = new Vector();

    public Table() {
        initComponents();
        vctHeader.add("Stock ID");
        vctHeader.add("Stock name");
        vctHeader.add("Address");
        vctHeader.add("Data Available");
        vctHeader.add("Note");

        Vector vctRow1 = new Vector();
        vctRow1.add("1");
        vctRow1.add("Stock one");
        vctRow1.add("1a");
        vctRow1.add("1a");
        vctRow1.add("1a");
        vctData.add(vctRow1);
        
        Vector vctRow2 = new Vector();
        vctRow2.add("2");
        vctRow2.add("Stock two");
        vctRow2.add("2a");
        vctRow2.add("2a");
        vctRow2.add("2a");
        vctData.add(vctRow2);

        Vector vctRow3 = new Vector();
        vctRow3.add("3");
        vctRow3.add("Stock three");
        vctRow3.add("3a");
        vctRow3.add("3a");
        vctRow3.add("3a");
        vctData.add(vctRow3);

        Vector vctRow4 = new Vector();
        vctRow4.add("4");
        vctRow4.add("Stock four");
        vctRow4.add("4a");
        vctRow4.add("4a");
        vctRow4.add("4a");
        vctData.add(vctRow4);
        table.setModel(new DefaultTableModel(vctData, vctHeader));
        if (!vctData.isEmpty()) {
            table.setRowSelectionInterval(0, 0);
        }
        length = table.getRowCount();
        setBtnByBoundary();
    }

    public boolean checkData() {
        if (length > 0) {
            return true;
        } else {
            btnfirst.setEnabled(false);
            btnprevious.setEnabled(false);
            btnnext.setEnabled(false);
            btnlast.setEnabled(false);
            return false;
        }
    }

    public void setBtnByBoundary() {
        int rowIndex = table.getSelectedRow();
        btnfirst.setEnabled(true);
        btnprevious.setEnabled(true);
        btnnext.setEnabled(true);
        btnlast.setEnabled(true);
        if (rowIndex < 0) {
            btnfirst.setEnabled(false);
            btnprevious.setEnabled(false);
            btnnext.setEnabled(false);
            btnlast.setEnabled(false);
        }
        if (rowIndex == 0) {
            btnfirst.setEnabled(false);
            btnprevious.setEnabled(false);
        }
        if (rowIndex == length - 1) {
            btnnext.setEnabled(false);
            btnlast.setEnabled(false);
        }
    }

    public void changeLine(int move) {
        int index = table.getSelectedRow();
        int newIndex = index + move;
        table.setRowSelectionInterval(newIndex, newIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnfirst = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        btnfirst.setText("Move First");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnprevious.setText("Move Previous");
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnnext.setText("Move Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setText("Move Last");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnfirst)
                .addGap(41, 41, 41)
                .addComponent(btnprevious)
                .addGap(46, 46, 46)
                .addComponent(btnnext)
                .addGap(42, 42, 42)
                .addComponent(btnlast)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfirst)
                    .addComponent(btnprevious)
                    .addComponent(btnnext)
                    .addComponent(btnlast))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
        if (checkData()) {
            table.setRowSelectionInterval(0, 0);
            setBtnByBoundary();
        }
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        if (checkData()) {
            changeLine(-1);
            setBtnByBoundary();
        }

    }//GEN-LAST:event_btnpreviousActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        if (checkData()) {
            changeLine(1);
            setBtnByBoundary();
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        if (checkData()) {
            table.setRowSelectionInterval(length - 1, length - 1);
            setBtnByBoundary();
        }
    }//GEN-LAST:event_btnlastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
